### ISSUE TITLE
Neighborhood Deprivation Index

### ISSUE THREAD

**Issue by achan53193** [degauss-org/dep_index#4]
I am interested in using DeGAUSS with my data to obtain census tract data information so that I can create a neighborhood deprivation index. I seen that DeGAUSS offers an deprivation index image that is linked to the 2018 American community survey variables. However, I would like to be able to link my geocodes to all of the census tract variable that are available. Is this something I can do with DeGAUSS, and if so how can this be done?

Thank you

**Comment by cole-brokamp** [comment]
Here's a protocol that was created for something similar that you could adopt: https://degauss.org/sheero.html  Essentially, use degauss-org/geocoder to convert addresses to coordinates, and then use degauss-org/census_block_group or degauss-org/st_census_tract to link census tract identifiers to coordinates given the right vintage of tract identifier. Lastly, you can link in any census data based on these identifiers.
