### ISSUE TITLE
Updating dep_index request

### ISSUE THREAD

**Issue by oliviamaras** [degauss-org/dep_index#5]
Hi! Would it be possible to update the container to use 2020 census tracts, and 2020 or beyond ACS data? Or instruct me how I can do this myself?

Thank you!

**Comment by cole-brokamp** [comment]
Hi, there is not a newer version of the deprivation index https://geomarker.io/dep_index available to link using newer data, but you could always use another degauss container to add on a census tract identifier and then use that to merge in any census tract level data that you would be interested in.

**Comment by oliviamaras** [comment]
Thank you!
